### ISSUE TITLE
Improvements needed for German language legal citation

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#75]
This is a list of missing features for Austrian styles of which most also are necessary for German styles.

- [x] Parallel citations might result in no printable form for a single parallel item in the note when a bibliography is added — _see_ https://github.com/Juris-M/zotero/issues/77.
- [x] String citations from the same court: the court name shouldn’t be repeated if the immediately preceding citation(s) refer to the same court. This is even true if different subdivisions of the same court are referred to — _see_ https://github.com/Juris-M/schema/commit/5a8d44b7b8de49af9ca63ab56f06d02cd92a623b#commitcomment-41511586.
- [ ] Short citations to statutary law should contain the amendment information only if more than one amended version is cited in the document (disambiguation).
- [x] In the bibliography, only the whole collection should be added, not every single comment. Some styles demand the same for edited books (only the whole book, not the single chapters to be put in the bibliography) — _see_ https://github.com/Juris-M/zotero/issues/76.
- [x] In legal case citations with commenters to the report, the commenter‘s attitude (affirms/criticises/doubts...) should be included before their name — _see_ https://github.com/Juris-M/zotero/issues/78.
- [ ] A locator `margin-number` is necessary for citing German legal literature — _see_ https://github.com/Juris-M/zotero/issues/82.

**Comment by denismaier** [comment]
>  In the bibliography, only the whole collection should be added, not every single comment. Some styles demand the same for edited books (only the whole book, not the single chapters to be put in the bibliography).

+1 from me. That's needed for sure. But, maybe we should aim for a solution in CSL proper for this, don't you think? (Although, honestly, that's another one of those arcane requirements that should just go away ;-))

**Comment by georgd** [comment]
> > In the bibliography, only the whole collection should be added, not every single comment. Some styles demand the same for edited books (only the whole book, not the single chapters to be put in the bibliography).
> 
> +1 from me. That's needed for sure. But, maybe we should aim for a solution in CSL proper for this, don't you think? (Although, honestly, that's another one of those arcane requirements that should just go away ;-))

So, it’s time for another issue at CSL/schema?

**Comment by denismaier** [comment]
> So, it’s time for another issue at CSL/schema?

Absolutely.

**Comment by georgd** [comment]
@denismaier could you perhaps verify if this is sufficient for Swiss styles as well and add to the list if not?

**Comment by bwiernik** [comment]
@georgd Issues are much more likely to be resolved if you write a CSL test for the issue, rather than just narratively describing them.

**Comment by georgd** [comment]
> @georgd Issues are much more likely to be resolved if you write a CSL test for the issue, rather than just narratively describing them. 

Ok, thanks for the hint. I I'll try to add them to the single issues linked to from here.

**Comment by fbennett** [comment]
I think we have all of these covered now.
- [ ] Parallel citations and no-printable-form (https://github.com/Juris-M/zotero/issues/77). Addressed by https://github.com/Juris-M/citeproc-js/commit/6c923257b83325890eab68c8aa3b0b4c5a869613
- [ ] Suppression of repetition of selected variable in consecutive unrelated items (https://github.com/Juris-M/schema/commit/5a8d44b7b8de49af9ca63ab56f06d02cd92a623b#commitcomment-41511586) Addressed by https://github.com/Juris-M/citeproc-js/commit/2c1f2eb2c6f0dfeb7cf5e62da814c2a0cae5800b
- [ ] Short citations to statutory law should contain the amendment information only if more than one amended version is cited in the document. Can be handled with `disambiguate="true"` condition.
- [ ] In the bibliography, only the whole collection should be added, not every single comment. (https://github.com/Juris-M/zotero/issues/76) _see_ https://github.com/Juris-M/zotero/issues/76
- [ ] In legal case citations with commenters to the report, the commenter‘s attitude (affirms/criticises/doubts...) should be included before their name (https://github.com/Juris-M/zotero/issues/78) Not sure about formatting issues, but can this also be handled via [locator-extra](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#locator-date-and-locator-extra-extension)?

**Comment by georgd** [comment]
Commentary collections in the bibliography still not, as we know ( #76 ).

For statutary law with amendments, I have `disambiguate="true"` in my code but it hasn’t shown up because my tests were bad. Now, it‘s flaky, coming and going. Still have to look more closely what’s happening, then I’ll open another issue.

**Comment by fbennett** [comment]
Closing this in favor of https://github.com/Juris-M/zotero/issues/81
